version: '3.4'

services:
  companymanagement.api:
    image: ${DOCKER_REGISTRY-}companymanagementapi
    container_name: company-management-api
    build:
      context: .
      dockerfile: src/CompanyManagement.Api/Dockerfile
    depends_on:
      - company-management-db

  company-management-db:
    image: postgres:latest
    container_name: company-management-db
    environment:
      - POSTGRES_DB=company_management_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5435:5432