version: '3.4'

services:
  companymanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5830
      - ASPNETCORE_HTTPS_PORTS=5831
    ports:
      - 5830:5830
      - 5831:5831
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro